# Generated by Django 4.1.2 on 2022-10-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwacu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='')),
                ('description', models.FileField(upload_to='')),
            ],
        ),
    ]
