# Generated by Django 4.1.2 on 2022-10-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwacu', '0002_diy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('names', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(default='male', max_length=255)),
                ('National_id', models.IntegerField(max_length=255)),
                ('phonenumber', models.CharField(default='947587986', max_length=255)),
            ],
        ),
    ]
